apiVersion: cloud.sndl.io/v1
kind: Sndl
metadata:
  name: sndl
  namespace: capacitacion
spec:
  crate:
    cluster:
      imageRegistry: crate
      name: crate
      version: 4.5.0
    nodes:
      data:
      - name: default
        replicas: 2
        resources:
          cpus: 0.5
          disk:
            count: 1
            size: 1GiB
            storageClass: default
          heapRatio: 0.5
          memory: 1GiB



